version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    env_file:
      - ../.env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: hstrprn/foodgram_backend:latest
    env_file:
      - ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: hstrprn/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  gateway:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../frontend/build:/usr/share/nginx/html/
      - static:/var/www/backend/static/
      - media:/mediafiles/
    depends_on:
      - backend
      - frontend
