version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    env_file:
      - ../.env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: hstrprn/foodgram_backend:latest
    env_file:
      - ../.env
    volumes:
      - static:/app/collected_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: hstrprn/foodgram_frontend:latest
    volumes:
      - static:/app/result_build/build
  gateway:
    image: hstrprn/foodgram_gateway:latest
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/

