# Generated by Django 4.2.4 on 2023-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingridient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
