# Generated by Django 4.2.4 on 2023-08-31 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingridient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingridients',
            name='ingredient_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки'),
        ),
    ]
