# Generated by Django 4.2.4 on 2023-08-31 23:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingridient_options_alter_ingridient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Колличество ингредиента')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridient',
        ),
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeIngridients',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='ingrideent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингрeдиент'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='+', through='recipes.RecipeIngredients', to='recipes.ingredient', verbose_name='Ингридиенты'),
        ),
    ]
