# Generated by Django 4.2.4 on 2023-09-05 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_image_remove_recipe_tags_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Укажите количество')], verbose_name='Колличество ингредиента'),
        ),
    ]
