# Generated by Django 4.2.4 on 2023-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_recipeingredient_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user',), 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart_constraint',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shopping_cart_constraint'),
        ),
    ]
