# Generated by Django 4.2.4 on 2023-09-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'name', 'image'), name='recipe_unique_constraint'),
        ),
    ]
