# Generated by Django 4.2.4 on 2023-09-28 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('([а-яА-ЯёЁ0-9]\\s[а-яА-ЯёЁ0-9]|[а-яА-ЯёЁ0-9])', message='Название тега может состоять только из русских букв и цифр')], verbose_name='Название'),
        ),
    ]
